### ISSUE TITLE
described-as-failed-output.eo:28-31: To add several tests...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-hamcrest#107]
The puzzle `41-3b9d114c` from #41 has to be resolved: 

https://github.com/objectionary/eo-hamcrest/blob/b27a1fb3a4550ea5dc1880f988a9d4ffe0f977e6/src/test/eo/org/eolang/hamcrest/failed-output/described-as-failed-output.eo#L28-L31

The puzzle was created by graur on 14-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@graur please pay attention to this new issue.

**Comment by Graur** [comment]
@includealex please, help us here
