### ISSUE TITLE
assert-twice-that

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-hamcrest#167]
Let's add a new object `assert-repeatedly-that`, which works similar to `assert-that` but makes a number of attempts to compare two objects. I would say, a random number of attempts between two and, say, five.

**Comment by Graur** [comment]
@yegor256 Will this object try to dataize this object multiple times?

**Comment by yegor256** [comment]
@Graur yes, it will dataize the object multiple times, each time making the comparison.

**Comment by yegor256** [comment]
@Graur let's call it `assert-twice-that` -- just do it twice, it will be enough

**Comment by Graur** [comment]
@yegor256 This test should pass, am I right?
```
[] > two-sum-test
  memory 0 > count
  [] > foo
    count.write (count.plus 1) > @
  assert-twice-that > @
    foo
    $.equal-to 2
```

**Comment by yegor256** [comment]
@Graur yes, correct

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#169](https://github.com/objectionary/eo-hamcrest/issues/169), [#170](https://github.com/objectionary/eo-hamcrest/issues/170), [#171](https://github.com/objectionary/eo-hamcrest/issues/171) are still not solved.
