### ISSUE TITLE
switch with is-close

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-hamcrest#172]
@Graur please take a look at these tests:
```
[] > check-switch-close-1
  assert-that > @
    switch
      *
        TRUE
        1.0
    $.close-to
      1.0
      0.1
```
```
[] > check-switch-close-2
  assert-that > @
    switch
      *
        TRUE
        1.0
    $.equal-to 1.0
``` 
The second test passes succesfully but the first fails with `stackoverflow` error. Seems like a bug.
I have also tested it in eo-hamcrest and the first test freezes and does not finish

**Comment by Graur** [comment]
@levBagryansky Indeed, thanks for noticing

**Comment by Graur** [comment]
@levBagryansky Looks like this test passes in #173. Maybe you have another example?

**Comment by levBagryansky** [comment]
@Graur It is passes but takes too long time.
I have pulled this repository, performed `rm -r .eo/` , added the tests above and enter `mvn clean test`. All tests but the `check-switch-close-1` has taken no more than 2 seconds. This test passed more than for 20s. Perhaps this effect was not seen by others. So I added a a little complicated tests 
```
[] > check-switch-close-3
  assert-that > @
    switch
      *
        TRUE
        switch
          *
            TRUE
            1.0
    $.close-to
      1.0
      0.1
```

```
[] > check-switch-close-4
  assert-that > @
    switch
      *
        TRUE
        switch
          *
            TRUE
            1.0
    $.equal-to
      1.0
```
`check-switch-close-4` still passes quite quickly in opposed to `check-switch-close-3`. 
And created [pr](https://github.com/objectionary/eo-hamcrest/pull/174) with `check-switch-close-3`. Please take a look at executing time of mvn checks.

**Comment by levBagryansky** [comment]
@Graur I did the same with more complicated test. You can see approximately same result here:
[switch in switch in switch with close-to](https://github.com/objectionary/eo-hamcrest/pull/176)
[switch in switch in switch with equal-to](https://github.com/objectionary/eo-hamcrest/pull/177)
Difference in timing is colossal
