### ISSUE TITLE
New release `0.3.0`

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-hamcrest#180]
We need to make a new release

**Comment by Graur** [comment]
@yegor256 Can you help with release new version of `eo-hamcrest`? I suggest `0.3.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by yegor256** [comment]
@Graur you need to add this: https://github.com/objectionary/eo-sys/blob/master/pom.xml#L85-L91

**Comment by 0pdd** [comment]
@Graur the puzzle [#183](https://github.com/objectionary/eo-hamcrest/issues/183) is still not solved.

**Comment by Graur** [comment]
@yegor256 Thanks! Can you create a new release again, please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by Graur** [comment]
@yegor256 Thanks!
