### ISSUE TITLE
Reflect `array` to `tuple` renaming

### ISSUE THREAD

**Issue by mximp** [objectionary/eo-hamcrest#193]
`array` object has been renamed to `tuple` in `eo-runtime`. It needs to be reflected in this lib.

**Comment by mximp** [comment]
@Graur please assist.

**Comment by Graur** [comment]
@yegor256 Can you help with the releasing of a new version? Since key word `array` doesn't exist. I suggest a `0.3.2` version but it's up to you

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.2`
