### ISSUE TITLE
`eo-collections` can't be version up in objectionaries because of `eo-hamcrest` tests

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-hamcrest#213]
This [build](https://github.com/objectionary/home/actions/runs/6405184948/job/17387218064?pr=183) fails because there are break changes in `eo-collections 0.10.0` related to [arguments order](https://github.com/objectionary/eo-collections/blob/0825ba8b387abf5a949e2ea54f2f4e0fcf62ca3d/src/test/eo/org/eolang/collections/list-tests.eo#L242-L245) in `list.reducedi`.

Need to change all `list.reducedi` uses in the repo, disable the tests, make new release and try to update `eo-hamcrest` in objectionary

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by maxonfjvipon** [comment]
@yegor256 could you please try to release one more time?

**Comment by maxonfjvipon** [comment]
@yegor256 could you please try to release one more time?

**Comment by yegor256** [comment]
@maxonfjvipon it's released: https://repo1.maven.org/maven2/org/eolang/eo-hamcrest/

**Comment by maxonfjvipon** [comment]
@yegor256 why isn't there a `0.5.0` tag on [github](https://github.com/objectionary/eo-hamcrest/releases)?

**Comment by maxonfjvipon** [comment]
@yegor256 please try to release with tag `0.5.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.1`

**Comment by yegor256** [comment]
@maxonfjvipon same story :( It's a bug inside Sonatype server (and their plugin maybe)
