### ISSUE TITLE
Update eolang.version to v0.32.0

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-hamcrest#218]
Pr #208 fails, so we need to do it manually.

**Comment by 0pdd** [comment]
@levBagryansky 8 puzzles [#221](https://github.com/objectionary/eo-hamcrest/issues/221), [#222](https://github.com/objectionary/eo-hamcrest/issues/222), [#223](https://github.com/objectionary/eo-hamcrest/issues/223), [#224](https://github.com/objectionary/eo-hamcrest/issues/224), [#225](https://github.com/objectionary/eo-hamcrest/issues/225), [#226](https://github.com/objectionary/eo-hamcrest/issues/226), [#227](https://github.com/objectionary/eo-hamcrest/issues/227), [#228](https://github.com/objectionary/eo-hamcrest/issues/228) are still not solved.

**Comment by levBagryansky** [comment]
@yegor256 can we release it since eo-runtime dependency was changed? to 0.5.1

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.1`
