### ISSUE TITLE
place objectionary.lst into gh-pages on every release

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-hamcrest#23]

**Comment by Graur** [comment]
@rultor release, tag is `0.1.1`

**Comment by Graur** [comment]
@rultor merge

**Comment by Graur** [comment]
@rultor release, tag is `0.1.1`

**Comment by Graur** [comment]
@rultor release, tag is 0.1.1

**Comment by Graur** [comment]
@rultor release, tag is `0.1.1`

**Comment by Graur** [comment]
@rultor release, tag is `0.1.2`

**Comment by Graur** [comment]
@rultor release, tag is `0.1.5`
