### ISSUE TITLE
+home and +version metas in all files

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-hamcrest#48]
Let's add `+home` and `+version` metas in all files, as it's done, for example, here: https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/bool.eo#L24-L25

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
