### ISSUE TITLE
new interface of "memory"

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-hamcrest#54]
Since 0.23.7 the way we work with `memory` has changed. Now, we should do it like this:

```
memory 0 > x
x.write 42
```

We should update the version of EO in this lib and release again.

**Comment by Graur** [comment]
@rultor release, tag is `0.2.2`

**Comment by Graur** [comment]
@rultor release, tag is `0.2.2`

**Comment by Graur** [comment]
@rultor release, tag is `0.2.3`

**Comment by Graur** [comment]
@yegor256 What would be this additional parameter `0` in memory? Why enclosure?

**Comment by Graur** [comment]
fixed
