### ISSUE TITLE
Can it use decorator?

### ISSUE THREAD

**Issue by Masynchin** [objectionary/eo-hamcrest#58]
Can this code use decorator?

https://github.com/objectionary/eo-hamcrest/blob/f8bb8406856db15ee8f677cd770cf1b33a3eaa79/src/main/eo/org/eolang/hamcrest/assert-that.eo#L221-L234

I am not an expert in EO, but I assume that it can be rewrite as:

~~~eo
[matcher] > is
  matcher > @

  [] > description-of
    sprintf > @
      "is %s"
      description-of.
        matcher
~~~

Let me know if I am wrong. If not, I can submit appropriate PR.

**Comment by Graur** [comment]
@Masynchin Yes, indeed, you are absolutely right. Thanks for noticing. You are welcome to submit a PR.

**Comment by Graur** [comment]
@Masynchin Thanks!
