### ISSUE TITLE
eo 0.23.15

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-hamcrest#64]
Version 0.23.15 has been release to Objectionary. I had to remove eo-hamcrest, since it didn't compile. Please, release a new version and submit a PR to Objectionary

**Comment by Graur** [comment]
@rultor release, tag is `0.2.5`

**Comment by Graur** [comment]
@rultor release, tag is `0.2.5`

**Comment by Graur** [comment]
@rultor release, tag is `0.2.5`

**Comment by Graur** [comment]
@rultor release, tag is `0.2.5`

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by Graur** [comment]
I believe we can close it, since new version was released.
