### ISSUE TITLE
`equal-to` object have to be an atom since `0.23.17`

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-hamcrest#71]
Since we got rid of object `array.eq` from `eo-runtime` we need to figure out how to compare arrays. And add some type checking.
Maybe `equal-to` could be an atom?

**Comment by Graur** [comment]
@yegor256 What do you think?

**Comment by yegor256** [comment]
@Graur I think `equal-to` should just use `.eq` of the provided object. In case of `array` it will just crash.

**Comment by Graur** [comment]
@yegor256 Thanks!
