### ISSUE TITLE
EO up to `0.23.17`

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-hamcrest#72]
We need to up `eo` version and fix bugs.

**Comment by yegor256** [comment]
@Graur version 0.23.17 released to objectionary

**Comment by Graur** [comment]
@rultor release, tag is `0.2.6`

**Comment by Graur** [comment]
@yegor256 Thanks!

**Comment by Graur** [comment]
@yegor256 please, help me to add this new version to objectionary/home.

**Comment by yegor256** [comment]
@Graur done

**Comment by Graur** [comment]
@yegor256 Thanks!
