### ISSUE TITLE
Hamcrest tries to access missing attribute `array.is-empty`

### ISSUE THREAD

**Issue by mximp** [objectionary/eo-hamcrest#74]
`is-empty` attributes has been recently moved to `collections.list` object.
However the lib still tries to use it in array:

```
# Main object for assertions
[actual matcher reasons...] > assert-that

  if. > @
    matcher.match actual
    TRUE
    sprintf
      "%s\nExpected: %s\n     but: %s"
      if.
        reasons.is-empty
...
```

`assert-that` object needs to be updated.

**Comment by Graur** [comment]
@mximp Indeed, thanks!

**Comment by Graur** [comment]
@mximp I think we can close this issue
