### ISSUE TITLE
Freeze when comparing different strings

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-hamcrest#80]
```
[] > some-test
  "abc" > a!
  assert-that > @
    a
    $.equal-to "abd"
```
Should return FALSE when comparing different strings, but instead it freezes.

**Comment by EugeneDar** [comment]
@Graur please check.

**Comment by Graur** [comment]
@EugeneDar I added this test here: https://github.com/objectionary/eo-hamcrest/blob/master/src/test/eo/org/eolang/hamcrest/not-tests.eo#L68-L74
And it passed. I think we can close this issue

**Comment by EugeneDar** [comment]
@Graur thank you
