### ISSUE TITLE
the build fails on Windows

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-hamcrest#87]
See GitHub Actions. It happens in some other EO libs. Maybe you can fix it.

**Comment by Graur** [comment]
@yegor256 Can you help me with a solution? I thought that `mvn.yaml` was incorrect, but now it is and this issue is still here.

**Comment by yegor256** [comment]
@Graur I believe the problem is related to the name of one file, which contains the "phi" symbol. On Windows it's not treated right, most probably because of wrong encoding. Maybe this will help: https://stackoverflow.com/a/388500/187141

**Comment by Graur** [comment]
@yegor256 Could you give me some advice on reproducing the problem in the `qulice-checkstyle` dependency? I think I have a solution to the current problem, but I can't figure out how to reproduce it. I tried to create a test that breaks a build on a colleague's computer with Windows, but it didn't work out.

**Comment by yegor256** [comment]
@Graur you an just create another integration test for qulice, in its `qulice-maven-plugin/src/it` directory, with a Unicode file name. I'm sure, it will break.

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions

**Comment by yegor256** [comment]
@Graur thanks!
