### ISSUE TITLE
Better way to output arrays

### ISSUE THREAD

**Issue by andreoss** [objectionary/eo-hamcrest#94]
arrays are converted to `String` by `.toString()` method, which renders them unreadable

Example:
```
Expected: <Hello, друг!
> equal to value
     but: was <[B@3a7e45e7>
```

Proposal: use `Arrays.toString()` instead

**Comment by Graur** [comment]
I think it is duplicate of: https://github.com/objectionary/eo-hamcrest/issues/36

**Comment by andreoss** [comment]
@Graur you are right
